name: Impossible Humans
favicon: null
layout_spectrum: 0.74639
typography_spectrum: 0.58634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#67738c'
    - '#674a52'
    - '#a6a6a6'
    - '#818181'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.26391991158016026
purpose: []
