typography_spectrum: 0.58634
color:
  brandColors:
    - '#404040'
    - '#67738c'
    - '#674a52'
    - '#a6a6a6'
    - '#818181'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.26391991158016026
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74639
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Impossible Humans
  email: theneweramuseum@gmail.com
  url: 'http://impossiblehumans.tumblr.com/'
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/e6d6fb38-73d1-4379-9860-fcc3c33d259f.jpg'
name: Impossible Humans
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca7cdeb0-ef1c-452e-9137-271fc5034c3f.jpg'
purpose: []
