name: Impossible Humans
favicon: null
layout_spectrum: 0.5247200902085751
typography_spectrum: 0.6996690698433667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03677552682347596
  lightness: 0.2219817906152457
  saturation: 0.12209490709938109
  rhythmicContrast: 0.26391991158016026
purpose: []
